/** Textos de Custos e de Rotinas no admin (E46 PR 3, passo 15 do Opus: `AdminCustos.dc.html` e `AdminJobs.dc.html`). Sem travessão, sem emoji, língua de gente. */

export const textosCustosAdmin = {
  titulo: "Custos",
  linha: (cambio: string, data: string) => `Em reais, com o dólar a R$ ${cambio} (câmbio de ${data}). Os 7 e os 30 dias vão até ontem; hoje fica à parte.`,
  semDado: {
    titulo: "Ainda não há custo para mostrar",
    texto: "O que varia aparece aqui depois da primeira madrugada. Os fixos só aparecem se alguém cadastrar: comece por eles, para o mês já sair com tudo.",
    botao: "Cadastrar o primeiro fixo",
  },
  contadores: { hoje: "hoje", hojePassou: "hoje, passou do teto", dias7: "nos últimos 7 dias", dias30: "em 30 dias, com os fixos", porRoteiro: "por roteiro", soVaria: "só o que varia", doQueVaria: (v: string) => `${v} do que varia`, roteiros30: (n: number) => (n === 1 ? "1 roteiro em 30 dias" : `${n} roteiros em 30 dias`), semRoteiro: "nenhum roteiro em 30 dias" },
  teto: {
    titulo: "O teto do dia",
    soVaria: "só o que varia",
    trocar: "Trocar o teto",
    linha: (hoje: string, teto: string, pct: number) => `Hoje ${hoje} de ${teto} por dia, ${pct}%`,
    passou: (hoje: string, teto: string) => `Hoje passou do teto: ${hoje} de ${teto}.`,
    maisGastou: (rotulo: string, valor: string, vezes: number) => `O que mais gastou foi ${rotulo.toLowerCase()}, ${valor}: rodou ${vezes} ${vezes === 1 ? "vez" : "vezes"} hoje.`,
    verRotinas: "Ver em Rotinas",
    nota: "Passar do teto não para nada: o sistema avisa aqui e no Início, e quem decide é você.",
    campo: "Teto por dia, em reais",
    salvar: "Salvar",
    cancelar: "Cancelar",
    erro: "Não deu para salvar o teto. Ele continua o de antes.",
  },
  porConta: {
    titulo: "Por conta",
    legenda: "o que varia, 30 dias",
    roteirosCada: (n: number, cada: string) => `${n} ${n === 1 ? "roteiro" : "roteiros"}, ${cada} cada`,
    semRoteiro: "nenhum roteiro",
    base: (valor: string) => `Mais ${valor} da base dos ramos (a busca de vídeos, a análise e a pesquisa de mercado), que não é de uma conta só.`,
    vazio: "Nenhuma conta gastou nos últimos 30 dias.",
    porRamoNota: "O custo por ramo ainda não é separado: a geração de IA não guarda de qual ramo veio.",
  },
  ondeVai: { titulo: "Por onde o dinheiro vai", legenda: "30 dias, o que varia", vazio: "Nada ainda.", vezes: (n: number) => (n === 1 ? "1 vez" : `${n} vezes`), semRegistro: "A transcrição e a busca de vídeos pagas por uso ainda não registram custo aqui: só a IA é medida." },
  fixos: {
    titulo: "Os fixos",
    legenda: "o que se paga todo mês, sem depender do uso",
    colunas: { oque: "O quê", valor: "Valor", porMes: "Por mês, em reais", cobra: "Cobra", acoes: "Ações" },
    adicionar: "Adicionar um fixo",
    editar: "Editar",
    tirar: "Tirar",
    confirmaTirar: (nome: string) => `Tirar ${nome} dos fixos? O que ele já custou continua nos meses que passaram.`,
    confirmar: "Tirar",
    cancelar: "Cancelar",
    salvar: "Salvar",
    campoNome: "O quê",
    campoValor: "Valor",
    campoMoeda: "Moeda",
    campoPeriodo: "Período",
    campoCobra: "Quando cobra",
    reais: "Reais",
    dolares: "Dólares",
    porMes: "Por mês",
    porAno: "Por ano",
    vazio: "Nenhum fixo cadastrado. Enquanto isso, o Início usa R$ 1.639 por mês, o valor da apresentação.",
    rodape: (valor: string) => `Por mês, com o dólar de hoje ${valor}`,
    nota: "O que é cobrado em dólar entra no mês pelo câmbio do dia. O que é anual entra dividido por 12.",
    erro: "Não deu para salvar. Confira o nome e o valor.",
    valorEm: (valor: string, moeda: "brl" | "usd", periodo: "mensal" | "anual") => `${moeda === "usd" ? "US$ " : "R$ "}${valor} ${periodo === "anual" ? "por ano" : "por mês"}`,
  },
};

export const textosRotinasAdmin = {
  titulo: "Rotinas",
  linha: (ramos: number, rotinas: number) => `O que o sistema faz sozinho, todo dia. Hoje: ${ramos === 1 ? "1 ramo" : `${ramos} ramos`}, ${rotinas} rotinas`,
  madrugada: {
    titulo: "A madrugada de hoje",
    legenda: (problemas: number, ramos: number, dia: string) => (ramos === 0 ? `${dia}: nenhum ramo ativo` : problemas === 0 ? `${dia}: tudo saiu ${ramos === 1 ? "no único ramo" : `nos ${ramos} ramos`}` : `${dia}: ${problemas === 1 ? "1 ramo com algo que não saiu" : `${problemas} ramos com algo que não saiu`}`),
    etapas: { busca: "Buscar vídeos", transcricao: "Transcrever", analise: "Analisar", temas: "Temas do dia" },
    videos: (n: number) => (n === 1 ? "1 novo" : `${n} novos`),
    transcritos: (n: number) => (n === 1 ? "1 transcrito" : `${n} transcritos`),
    analisados: (n: number) => (n === 1 ? "1 vídeo" : `${n} vídeos`),
    temas: (n: number) => (n === 1 ? "1 tema" : `${n} temas`),
    naoSaiu: "não saiu",
    aindaNao: "ainda não",
    rotinasGlobais: "A busca e a transcrição rodam para todos os ramos de uma vez",
    vazio: "Nenhum ramo ativo ainda.",
  },
  rotinas: {
    titulo: "As rotinas",
    legenda: (n: number) => `${n}, a última vez de cada uma`,
    estado: { ok: "deu certo", erro: "falhou", rodando: "rodando", nunca: "nunca rodou" },
    quando: "Quando",
    ultima: "Última vez",
    resultado: "Resultado",
    detalhe: "Ver o detalhe",
    nomeNoSistema: "Nome no sistema",
    comecou: "Começou",
    terminou: "Terminou",
    duracao: "Duração",
    oQueFalhou: "O que falhou, como veio",
    ultimasVezes: "As últimas vezes",
    semExecucao: "Ainda não rodou.",
    porEvento: "roda quando acontece o evento, não por horário",
    tentarDeNovo: "Rodar agora",
    aindaRodando: "rodando",
    taxa: (dev: number, cons: number, novos: number, fora: number, pct: string) => `devolvidos ${dev}, consumidos ${cons}, novos ${novos}, fora da curva ${fora}, taxa de acerto ${pct}`,
  },
};
