export const textosAdmin = {
  navegacao: {
    equipe: "Equipe",
    clientes: "Clientes",
    nichos: "Nichos",
    jobs: "Jobs",
  },
  clientes: {
    titulo: "Clientes",
    subtitulo: (n: number) => (n === 1 ? "1 cliente" : `${n} clientes`),
    buscar: "buscar por nome",
    colunaNegocio: "negócio",
    colunaNicho: "nicho",
    colunaNota: "nota do briefing",
    colunaUltimoRoteiro: "último roteiro",
    colunaDiasSemGravar: "dias sem gravar",
    semNicho: "sem nicho",
    semNota: "sem nota",
    semRoteiro: "sem roteiro ainda",
    diasAtencao: (n: number) => `${n} dias, atenção`,
    botaoAbrir: "abrir",
    vazio: "Nenhum cliente ainda. Convide o primeiro para começar.",
    semResultado: "nenhum cliente com esse nome",
    erro: "não conseguimos carregar a lista agora; tente de novo em um minuto",
    botaoTentarDeNovo: "tentar de novo",
    convidar: "convidar cliente",
    modalTitulo: "Convidar cliente",
    campoNome: "nome",
    campoEmail: "e-mail",
    campoNicho: "nicho",
    botaoConvidar: "convidar por e-mail",
    convidando: "convidando",
    sucesso: (email: string) => `cliente criado; o convite foi mandado para ${email}`,
    erroConvite: "não conseguimos criar o cliente; confira os dados e tente de novo",
  },
  nichos: {
    titulo: "Nichos",
    subtitulo: (n: number) => (n === 1 ? "1 nicho" : `${n} nichos`),
    colunaNome: "nome",
    colunaVideos: "vídeos no banco",
    colunaContas: "contas vigiadas",
    colunaUltimaLeitura: "última leitura",
    colunaEstado: "estado",
    nuncaLeu: "ainda não leu",
    ativo: "ativo",
    inativo: "inativo",
    vazio: "Um nicho reúne os clientes de um mesmo setor e define de onde vêm os temas do dia.",
    erro: "não conseguimos carregar a lista agora; tente de novo em um minuto",
  },
  jobs: {
    titulo: "Jobs",
    subtitulo: (n: number) => (n === 1 ? "1 execução" : `${n} execuções`),
    filtroTodos: "todos",
    colunaJob: "job",
    colunaInicio: "início",
    colunaDuracao: "duração",
    colunaEstado: "estado",
    colunaResumo: "resumo",
    estadoRodando: "rodando",
    estadoOk: "ok",
    estadoErro: "erro",
    vazio: "Nenhuma execução ainda.",
    erro: "não conseguimos carregar a lista agora; tente de novo em um minuto",
    botaoTentarDeNovo: "tentar de novo",
    botaoDisparar: (nome: string) => `disparar ${nome}`,
    disparando: "enfileirando",
    sucesso: "job enfileirado; o worker processa em instantes",
    erroDisparar: (mensagem: string) => `não conseguimos disparar o job: ${mensagem}`,
  },
};
