/**
 * "6 set" (E27 parte 2, item 5, AdminCliente.dc.html: dia mais mes abreviado,
 * sem ano). O Intl do Node devolve "6 de set.", com "de" e ponto; o design
 * nao tem nenhum dos dois.
 */
function formatarDiaMesAbreviado(data: Date): string {
  return new Intl.DateTimeFormat("pt-BR", { day: "numeric", month: "short", timeZone: "America/Sao_Paulo" })
    .format(data)
    .replace(" de ", " ")
    .replace(".", "");
}

export const textosAdmin = {
  navegacao: {
    equipe: "Equipe",
    clientes: "Clientes",
    nichos: "Nichos",
    jobs: "Jobs",
    geracoes: "Gerações",
    sair: "sair",
    saindo: "saindo",
  },
  clientes: {
    titulo: "Clientes",
    subtitulo: (n: number) => (n === 1 ? "1 cliente" : `${n} clientes`),
    buscar: "buscar por nome",
    colunaNegocio: "negócio",
    colunaNicho: "nicho",
    colunaNota: "nota do briefing",
    colunaUltimoRoteiro: "último roteiro",
    colunaDiasSemGravar: "dias sem gravar",
    semNicho: "sem nicho",
    semNota: "sem nota",
    semRoteiro: "sem roteiro ainda",
    diasAtencao: (n: number) => `${n} dias, atenção`,
    botaoAbrir: "abrir",
    vazio: "Nenhum cliente ainda. Convide o primeiro para começar.",
    semResultado: "nenhum cliente com esse nome",
    convidar: "convidar cliente",
    modalTitulo: "Convidar cliente",
    campoNome: "nome",
    campoEmail: "e-mail",
    campoNicho: "nicho",
    botaoConvidar: "convidar por e-mail",
    convidando: "convidando",
    sucesso: (email: string) => `cliente criado; o convite foi mandado para ${email}`,
    erroConvite: "não conseguimos criar o cliente; confira os dados e tente de novo",
  },
  nichos: {
    titulo: "Nichos",
    subtitulo: (n: number) => (n === 1 ? "1 nicho" : `${n} nichos`),
    colunaNome: "nome",
    colunaVideos: "vídeos no banco",
    colunaContas: "contas vigiadas",
    colunaUltimaLeitura: "última leitura",
    colunaEstado: "estado",
    nuncaLeu: "ainda não leu",
    ativo: "ativo",
    inativo: "inativo",
    vazio: "Um nicho reúne os clientes de um mesmo setor e define de onde vêm os temas do dia.",
    novoNicho: "novo nicho",
    modalTitulo: "Novo nicho",
    campoNome: "nome",
    campoDescricao: "descrição curta",
    campoTermos: "termos de busca",
    ajudaTermos: "um por linha, de 5 a 20",
    botaoCriar: "criar nicho",
    criando: "criando",
    erroCriar: "não conseguimos criar o nicho",
  },
  nichoDetalhe: {
    voltar: "nichos",
    naoEncontrado: "nicho não encontrado",
    foraDaCurvaTitulo: "fora da curva, últimos 90 dias",
    subindoHojeTitulo: "subindo hoje",
    vigilanciaTitulo: "lista de vigilância",
    colunaPlataforma: "plataforma",
    colunaConta: "conta",
    colunaViews: "views",
    colunaForaDaCurva: "fora da curva",
    colunaVelocidadeRelativa: "velocidade relativa",
    colunaTaxa: "taxa fora da curva",
    colunaMediana: "mediana de views",
    colunaAviso: "aviso",
    verVideo: "ver vídeo",
    semDado: "sem dado ainda",
    vazioForaDaCurva: "nenhum vídeo fora da curva ainda; o job pontuar roda todo dia, depois das coletas.",
    vazioSubindoHoje: "nada subindo agora; volte em algumas horas.",
    vazioVigilancia: "nenhuma conta vigiada ainda; adicione uma conta semente ou espere o job vigilancia, que roda todo domingo.",
    verModelo: "modelo do nicho",
    temasHojeTitulo: "temas de hoje",
    vazioTemasHoje: "nenhum tema hoje ainda; o job temasDoDia roda todo dia às 05:30.",
    evidenciasTitulo: "evidências",
    verGeracao: "ver geração em jobs",
    configuracaoTitulo: "configuração",
    ativo: "ativo",
    inativo: "inativo",
    editar: "editar",
    cancelar: "cancelar",
    salvar: "salvar",
    salvando: "salvando",
    campoNome: "nome",
    campoDescricao: "descrição curta",
    campoTermos: "termos de busca",
    ajudaTermos: "um por linha, de 5 a 20",
    sucessoSalvar: "salvo",
    ativar: "ativar nicho",
    desativar: "desativar nicho",
    contasSementeTitulo: "acrescentar conta semente",
    contasSementeAjuda: "cole até 10 links de perfil, um por linha (YouTube, TikTok ou Instagram)",
    campoContasSemente: "links de perfil",
    botaoAdicionarContas: "adicionar",
    adicionandoContas: "adicionando",
    sucessoContas: (n: number) => (n === 1 ? "1 conta semente adicionada" : `${n} contas semente adicionadas`),
    coletarAgoraTitulo: "coleta deste nicho",
    coletarAgora: "coletar agora",
    coletando: "pedindo a coleta",
    sucessoColetar: "coleta pedida; começa em instantes",
    duplicadoColetar: (nomes: string[]) => `já estava na fila: ${nomes.join(", ")}`,
    erroColetar: (mensagem: string) => `não conseguimos enfileirar a coleta: ${mensagem}`,
    ultimaExecucaoJob: (nome: string, quando: string) => `${nome}: ${quando}`,
    semExecucao: "ainda não rodou",
    estoqueTitulo: "estoque por plataforma",
    colunaContasComMediana: "contas com mediana",
    colunaOrigemMediana: "conta / seguidores / setor",
    colunaVideosComMultiplo: "vídeos com múltiplo",
    colunaOrigem: "origem",
    colunaUltimaLeituraApi: "última leitura pela api",
    origemApi: "api",
    origemApify: "apify",
    naoAplicavel: "não se aplica",
    metaStatusTitulo: "status da api da meta",
    colunaMetaLimite: "limite",
    colunaMetaUso: "uso",
    metaChamadasNaHora: "chamadas na hora",
    metaHashtagsNaSemana: "hashtags na semana",
  },
  nichoModelo: {
    voltar: "nicho",
    naoEncontrado: "nicho não encontrado",
    titulo: "Modelo do nicho",
    semana: (data: string) => `semana de ${data}`,
    baseadoEm: (n: number, acimaDoLimiar: number) =>
      `baseado em ${n} vídeo${n === 1 ? "" : "s"}, ${acimaDoLimiar} fora da curva`,
    vazio: "nenhum modelo ainda; o job modeloNicho roda todo domingo, depois da análise visual.",
    resumoTitulo: "resumo",
    ganchosTitulo: "ganchos",
    ganchoFrequencia: (frequencia: string) => `frequência: ${frequencia}`,
    duracaoTitulo: "duração típica",
    duracaoValor: (min: number, max: number) => `${min} a ${max} segundos`,
    estruturasTitulo: "estruturas",
    fechamentosTitulo: "fechamentos",
    chamadasFinaisTitulo: "chamadas finais",
    formatosTitulo: "formatos",
    edicaoTitulo: "edição",
    edicaoTextoNaTela: "texto na tela",
    edicaoRitmoDeCorte: "ritmo de corte",
    edicaoRecursos: "recursos",
    edicaoAudio: "áudio",
    semPadrao: "nenhum padrão identificado",
    assuntosQuentesTitulo: "assuntos quentes",
    audiosDaSemanaTitulo: "áudios da semana",
    vazioAudiosDaSemana: "nenhum áudio identificado nos vídeos fora da curva desta semana.",
    audioContagem: (n: number) => (n === 1 ? "1 vídeo" : `${n} vídeos`),
    audioSemNome: "áudio sem nome identificado",
    audioSemAutor: "autor não identificado",
    verVideoDeExemplo: "ver vídeo de exemplo",
  },
  jobs: {
    titulo: "Jobs",
    subtitulo: (n: number) => (n === 1 ? "1 execução" : `${n} execuções`),
    filtroTodos: "todos",
    colunaJob: "job",
    colunaInicio: "início",
    colunaDuracao: "duração",
    colunaEstado: "estado",
    colunaResumo: "resumo",
    /** So preenchidas nas execucoes de coleta paga do apify (E6 parte 3, terceira rodada, item 5). */
    colunaDevolvidos: "devolvidos",
    colunaConsumidos: "consumidos",
    colunaNovos: "novos",
    colunaForaDaCurva: "fora da curva",
    colunaTaxaDeAcerto: "taxa de acerto",
    estadoRodando: "rodando",
    estadoOk: "ok",
    estadoErro: "erro",
    vazio: "Nenhuma execução ainda.",
    botaoDisparar: (nome: string) => `disparar ${nome}`,
    disparando: "enfileirando",
    sucesso: "job enfileirado; o worker processa em instantes",
    erroDisparar: (mensagem: string) => `não conseguimos disparar o job: ${mensagem}`,
  },
  clienteDetalhe: {
    voltar: "clientes",
    naoEncontrado: "cliente não encontrado",
    briefingTitulo: "briefing",
    briefingCompleto: "completo",
    briefingIncompleto: "incompleto",
    semBriefing: "ainda não começou o briefing",
    notaGeral: "nota geral",
    saudeTitulo: "saúde da conta",
    roteirosTitulo: "roteiros",
    colunaData: "data",
    colunaTema: "tema",
    colunaStatus: "estado",
    vazioRoteiros: "nenhum roteiro ainda",
    /** E27 parte 2, item 5: "O que ele já reprovou", AdminCliente.dc.html. So leitura. */
    aprendizadoTitulo: "o que ele já reprovou",
    aprendizadoQuantos: (reprovacoes: number, ativas: number) =>
      `${reprovacoes === 1 ? "1 reprovação" : `${reprovacoes} reprovações`}, ${ativas === 1 ? "1 regra ativa" : `${ativas} regras ativas`}`,
    aprendizadoDeOnde: (contagem: number, ultimaEm: Date, motivo: string | null) => {
      const base =
        contagem === 1
          ? `1 reprovação, em ${formatarDiaMesAbreviado(ultimaEm)}`
          : `${contagem} reprovações, a última em ${formatarDiaMesAbreviado(ultimaEm)}`;
      return motivo ? `${base}. Motivo: ${motivo}.` : `${base}.`;
    },
    aprendizadoEtiquetaAtiva: "ativa",
    aprendizadoEtiquetaDesativada: "desativada",
    aprendizadoDesativadaEm: (desativadaEm: Date) =>
      `Desligada por ele em ${formatarDiaMesAbreviado(desativadaEm)}. Não entra mais no prompt.`,
    aprendizadoRodape:
      "As regras ativas entram no prompt do roteiro e do tema deste cliente. Nunca saem daqui: não entram no modelo do nicho.",
    aprendizadoVazio: "ainda nenhuma reprovação",
  },
  geracoes: {
    titulo: "Gerações",
    /** Segue o mesmo período e filtro do resumo (rodada de acabamento de 06/09, item 5). */
    subtitulo: (n: number, dias: number) =>
      n === 1 ? `1 geração em ${dias} dias` : `${n} gerações em ${dias} dias`,
    colunaData: "data",
    colunaTarefa: "tarefa",
    colunaModelo: "modelo",
    colunaCusto: "custo",
    colunaPrompt: "prompt",
    colunaAvaliacao: "avaliação",
    semAvaliacao: "sem avaliação",
    vazio: "Nenhuma geração ainda; toda chamada de IA fica registrada aqui.",
    voltar: "gerações",
    naoEncontrada: "geração não encontrada",
    entradaTitulo: "o que entrou",
    saidaTitulo: "o que saiu",
    semSaida: "sem saída registrada",
    evidenciasTitulo: "evidências usadas",
    semEvidencia: "nenhuma",
    periodo7: "7 dias",
    periodo30: "30 dias",
    filtroTarefaRotulo: "tarefa",
    filtroTarefaTodas: "todas as tarefas",
    filtroClienteRotulo: "cliente",
    filtroClienteTodos: "todos os clientes",
    resumoTitulo: (n: number) => (n === 1 ? "resumo, 1 geração" : `resumo, ${n} gerações`),
    resumoVazio: "nenhuma geração neste período com esse filtro.",
    custoTotal: "quanto custou",
    custoMedio: "custo médio por geração",
    tokensTitulo: "tokens",
    tokensEntrada: "entrada",
    tokensSaida: "saída",
    tokensCache: "cache",
    proporcaoCache: (percentual: string) => `${percentual} veio do cache`,
    taxasTitulo: "o que os clientes acharam",
    taxaGostaram: "gostaram",
    taxaNaoGostaram: "não gostaram",
    taxaReprovado: "reprovaram",
    /** Fluxo antigo (etapa 11), antes da E27; só aparece enquanto houver linha antiga no período. */
    taxaOutroAngulo: "pediram outro ângulo (antes da E27)",
    semAvaliacaoAinda: "nenhuma geração avaliada ainda neste período.",
    /** E27, parte 1, item 6: motivo estruturado, no lugar do texto livre de "outro ângulo". */
    motivosReprovadoTitulo: "por que reprovaram",
    /** Fluxo antigo (etapa 11), antes da E27; só aparece enquanto houver linha antiga no período. */
    motivosTitulo: "por que pediram outro ângulo (antes da E27)",
    semMotivos: "nenhum motivo registrado ainda.",
    custoPorClienteTitulo: "por cliente, últimos 30 dias",
    custoPorClienteVazio: "nenhum cliente com geração nos últimos 30 dias.",
    colunaCliente: "cliente",
    colunaCustoMes: "custo no mês",
    meta: (usd: string, brl: string) => `meta: ${usd} (${brl}, câmbio de agosto de 2026)`,
    acimaDaMeta: "acima da meta",
  },
};
