/** Textos de Custos e de Rotinas no admin (E46 PR 3, passo 15 do Opus: `AdminCustos.dc.html` e `AdminJobs.dc.html`). Sem travessão, sem emoji, língua de gente. */

export const textosCustosAdmin = {
  titulo: "Custos",
  linha: (cambio: string, data: string) => `Em reais, com o dólar a R$ ${cambio} (câmbio de ${data}). Os 7 e os 30 dias vão até ontem; hoje fica à parte.`,
  semDado: {
    titulo: "Ainda não há custo para mostrar",
    texto: "O que varia aparece aqui depois da primeira madrugada. Os fixos só aparecem se alguém cadastrar: comece por eles, para o mês já sair com tudo.",
    botao: "Cadastrar o primeiro fixo",
  },
  contadores: { hoje: "hoje", hojePassou: "hoje, passou do teto", dias7: "nos últimos 7 dias", dias30: "em 30 dias, com os fixos", porRoteiro: "por roteiro", soVaria: "só o que varia", doQueVaria: (v: string) => `${v} do que varia`, incluiEstimado: "inclui valores estimados", roteiros30: (n: number) => (n === 1 ? "1 roteiro em 30 dias" : `${n} roteiros em 30 dias`), semRoteiro: "nenhum roteiro em 30 dias" },
  teto: {
    titulo: "O teto do dia",
    soVaria: "só o que varia",
    trocar: "Trocar o teto",
    linha: (hoje: string, teto: string, pct: number) => `Hoje ${hoje} de ${teto} por dia, ${pct}%`,
    passou: (hoje: string, teto: string) => `Hoje passou do teto: ${hoje} de ${teto}.`,
    maisGastou: (rotulo: string, valor: string, vezes: number) => `O que mais gastou foi ${rotulo.toLowerCase()}, ${valor}: rodou ${vezes} ${vezes === 1 ? "vez" : "vezes"} hoje.`,
    verRotinas: "Ver em Rotinas",
    nota: "Passar do teto não para nada: o sistema avisa aqui e no Início, e quem decide é você.",
    campo: "Teto por dia, em reais",
    salvar: "Salvar",
    cancelar: "Cancelar",
    erro: "Não deu para salvar o teto. Ele continua o de antes.",
  },
  porConta: {
    titulo: "Por conta",
    legenda: "o que varia, 30 dias",
    roteirosCada: (n: number, cada: string) => `${n} ${n === 1 ? "roteiro" : "roteiros"}, ${cada} cada`,
    semRoteiro: "nenhum roteiro",
    base: (valor: string) => `Mais ${valor} da base dos ramos (a busca de vídeos, a análise e a pesquisa de mercado), que não é de uma conta só.`,
    vazio: "Nenhuma conta gastou nos últimos 30 dias.",
    porRamoNota: "O custo de cada ramo está logo abaixo, em Por ramo.",
  },
  porRamo: {
    titulo: "Por ramo",
    legenda: "IA e serviços pagos, 30 dias",
    vazio: "Nenhum ramo gastou nos últimos 30 dias.",
    detalhe: (ia: string, fora: string) => `IA ${ia}, fora da IA ${fora}`,
    incluiEstimado: "inclui valores estimados",
    semRamo: (valor: string) => `Mais ${valor} que não é de um ramo só (a lista de contas do mercado, as telas de lembrar a agenda e o que rodou para todos os ramos de uma vez).`,
  },
  foraDaIA: {
    titulo: "Fora da IA",
    legenda: "o que se paga por uso, 30 dias",
    vazio: "Nada registrado ainda. A transcrição e a busca de vídeos passam a aparecer aqui a partir da próxima madrugada.",
    minutos: (n: number) => `${n.toLocaleString("pt-BR", { maximumFractionDigits: 1 })} minutos de áudio`,
    resultados: (n: number) => `${n.toLocaleString("pt-BR", { maximumFractionDigits: 0 })} resultados`,
    vezes: (n: number) => (n === 1 ? "1 chamada" : `${n} chamadas`),
    estimado: "valor estimado pelo preço de tabela",
    daApi: "valor que o próprio serviço informou",
    nota: (dataApify: string) => `Transcrição: US$ 0,04 por hora de áudio, com o mínimo de 10 segundos por pedido. Busca de vídeos: o que o Apify informa por execução; quando ele não informa, o preço do ator (tabela de ${dataApify}). O teto do dia continua contando só a IA.`,
  },
  ondeVai: { titulo: "Por onde o dinheiro vai", legenda: "30 dias, o que varia", vazio: "Nada ainda.", vezes: (n: number) => (n === 1 ? "1 vez" : `${n} vezes`), semRegistro: "Só a IA entra nesta lista; o que se paga por uso fora dela está em Fora da IA." },
  fixos: {
    titulo: "Os fixos",
    legenda: "o que se paga todo mês, sem depender do uso",
    colunas: { oque: "O quê", valor: "Valor", porMes: "Por mês, em reais", cobra: "Cobra", acoes: "Ações" },
    adicionar: "Adicionar um fixo",
    editar: "Editar",
    tirar: "Tirar",
    confirmaTirar: (nome: string) => `Tirar ${nome} dos fixos? O que ele já custou continua nos meses que passaram.`,
    confirmar: "Tirar",
    cancelar: "Cancelar",
    salvar: "Salvar",
    campoNome: "O quê",
    campoValor: "Valor",
    campoMoeda: "Moeda",
    campoPeriodo: "Período",
    campoCobra: "Quando cobra",
    reais: "Reais",
    dolares: "Dólares",
    porMes: "Por mês",
    porAno: "Por ano",
    vazio: (padrao: string) => `Nenhum fixo cadastrado. Enquanto isso, o Início usa ${padrao} por mês, o valor da apresentação.`,
    rodape: (valor: string) => `Por mês, com o dólar de hoje ${valor}`,
    nota: "O que é cobrado em dólar entra no mês pelo câmbio do dia. O que é anual entra dividido por 12.",
    erro: "Não deu para salvar. Confira o nome e o valor.",
    valorEm: (valor: string, moeda: "brl" | "usd", periodo: "mensal" | "anual") => `${moeda === "usd" ? "US$ " : "R$ "}${valor} ${periodo === "anual" ? "por ano" : "por mês"}`,
  },
};

export const textosRotinasAdmin = {
  titulo: "Rotinas",
  linha: (ramos: number, rotinas: number) => `O que o sistema faz sozinho, todo dia. Hoje: ${ramos === 1 ? "1 ramo" : `${ramos} ramos`}, ${rotinas} rotinas`,
  madrugada: {
    titulo: "A madrugada de hoje",
    legenda: (problemas: number, ramos: number, dia: string) => (ramos === 0 ? `${dia}: nenhum ramo ativo` : problemas === 0 ? `${dia}: tudo saiu ${ramos === 1 ? "no único ramo" : `nos ${ramos} ramos`}` : `${dia}: ${problemas === 1 ? "1 ramo com algo que não saiu" : `${problemas} ramos com algo que não saiu`}`),
    etapas: { busca: "Buscar vídeos", transcricao: "Transcrever", analise: "Analisar", temas: "Temas do dia" },
    videos: (n: number) => (n === 1 ? "1 novo" : `${n} novos`),
    transcritos: (n: number) => (n === 1 ? "1 transcrito" : `${n} transcritos`),
    analisados: (n: number) => (n === 1 ? "1 vídeo" : `${n} vídeos`),
    temas: (n: number) => (n === 1 ? "1 tema" : `${n} temas`),
    naoSaiu: "não saiu",
    aindaNao: "ainda não",
    rotinasGlobais: "A busca e a transcrição rodam para todos os ramos de uma vez; hoje",
    buscaGlobal: "a busca",
    transcricaoGlobal: "a transcrição",
    vazio: "Nenhum ramo ativo ainda.",
  },
  rotinas: {
    titulo: "As rotinas",
    legenda: (n: number) => `${n}, a última vez de cada uma`,
    estado: { ok: "deu certo", erro: "falhou", rodando: "rodando", nunca: "nunca rodou" },
    quando: "Quando",
    ultima: "Última vez",
    resultado: "Resultado",
    detalhe: "Ver o detalhe",
    nomeNoSistema: "Nome no sistema",
    comecou: "Começou",
    terminou: "Terminou",
    duracao: "Duração",
    oQueFalhou: "O que falhou, como veio",
    ultimasVezes: "As últimas vezes",
    semExecucao: "Ainda não rodou.",
    porEvento: "roda quando acontece o evento, não por horário",
    tentarDeNovo: "Rodar agora",
    falhouEm: (nome: string, quando: string, frase: string) => `${nome.charAt(0).toUpperCase()}${nome.slice(1)} falhou ${quando}. ${frase}`,
    paradoNoLimite: "Parou no limite da Meta e continua na hora seguinte.",
    soUmRamo: "Rodar de novo só um ramo",
    escolhaORamo: "Escolha o ramo",
    rodarRamo: "Rodar só este ramo",
    deUmRamo: (nome: string) => `só o ramo ${nome}`,
    deTodosOsRamos: "todos os ramos",
    rodadaAMao: (quem: string | null, quando: string) => `Rodada à mão por ${quem ?? "alguém da equipe"}, ${quando}.`,
    aindaRodando: "rodando",
    taxa: (dev: number, cons: number, novos: number, fora: number, pct: string) => `devolvidos ${dev}, consumidos ${cons}, novos ${novos}, fora da curva ${fora}, taxa de acerto ${pct}`,
  },
};
