export const textosConta = {
  titulo: "Conta",
  nome: "nome",
  email: "e-mail",
  soLeitura: "(só leitura)",
  redes: "perfis nas redes",
  lembrete: "a que horas você quer o lembrete de gravar?",
  erroHoraForaDaFaixa: "escolha uma hora entre 6h e 22h",
  tema: "tema",
  temas: [
    { valor: "claro", rotulo: "claro" },
    { valor: "escuro", rotulo: "escuro" },
    { valor: "sistema", rotulo: "do sistema" },
  ],
  salvar: "salvar",
  salvando: "salvando",
  salvo: "salvo",
  sair: "sair",
  saindo: "saindo",
  erro: "não conseguimos salvar agora; tente de novo em um minuto",
};
