/** `/referencias` (etapa 12, brief-frontend.md 6.6, `ReferenciasTela.dc.html`). */
export const textosReferencias = {
  titulo: "Referências",
  linha: "os vídeos fora da curva no seu setor, os mais recentes primeiro",
  grupoPlataforma: "plataforma",
  grupoPeriodo: "período",
  grupoFormato: "formato",
  plataformas: ["todas", "YouTube", "TikTok", "Instagram"],
  periodos: ["esta semana", "30 dias", "90 dias"],
  formatos: ["fala para câmera", "podcast", "caixinha de pergunta", "esquete", "outro"],
  favoritos: "favoritos",
  acimaDoNormal: "acima do normal da conta",
  analise: { comecou: "Como começou", construiu: "Como construiu", funcionou: "Por que funcionou" },
  usar: "usar como referência",
  salvar: "salvar nos favoritos",
  salvando: "salvando",
  remover: "remover dos favoritos",
  toast: "salvo; entra como referência no seu briefing",
  vazio: "Os vídeos que estão funcionando no seu setor aparecem aqui depois da primeira leitura, que roda de madrugada.",
  semResultado: "nada nesse filtro; tente 90 dias",
  ver90: "ver 90 dias",
  abrirVideo: "abrir o vídeo",
  contaNaoIdentificada: "conta não identificada",
  embedAlt: (conta: string) => `vídeo de ${conta}, 9 por 16, carrega ao entrar na tela`,
  embedCarregando: "vídeo embedado 9:16 · carrega ao entrar na tela",
};
